@startuml
class com.library.exception.DataNotFoundException {
}
class com.library.service.ReaderService {
- ReaderRepository readerRepository
+ List<Reader> getAllReaders()
+ Reader getReaderById(String)
+ void registerReader(Reader)
+ void updateReader(String,Reader)
+ void deleteReader(String)
+ void updateReaderInfo(Reader)
- void validateReaderData(String,String)
}


class com.library.service.BookService {
- BookRepository bookRepository
+ List<Book> getAllBooks()
+ Book getBookById(String)
+ void addBook(Book)
+ void updateBook(String,Book)
+ void deleteBook(String)
+ void updateBookQuantity(String,int)
}


class com.library.exception.BorrowLimitExceededException {
}
class com.library.dto.ReturnRequestDTO {
- String readerId
- String bookId
+ String getReaderId()
+ void setReaderId(String)
+ String getBookId()
+ void setBookId(String)
}


class com.library.config.SecurityConfig {
+ SecurityFilterChain securityFilterChain(HttpSecurity)
}

interface com.library.service.policy.FinePolicy {
~ double calculateFine(int)
}

class com.library.model.BorrowRecord {
- String readerId
- String bookId
- int quantity
- String borrowDate
- String dueDate
+ String getReaderId()
+ void setReaderId(String)
+ String getBookId()
+ void setBookId(String)
+ int getQuantity()
+ void setQuantity(int)
+ String getBorrowDate()
+ void setBorrowDate(String)
+ String getDueDate()
+ void setDueDate(String)
}


class com.library.service.policy.LecturerFinePolicy {
- {static} double FINE_PER_DAY
+ double calculateFine(int)
}


class com.library.dto.BorrowRequestDTO {
- String readerId
- String bookId
- Integer quantity
+ String getReaderId()
+ void setReaderId(String)
+ String getBookId()
+ void setBookId(String)
+ Integer getQuantity()
+ void setQuantity(Integer)
}


class com.library.service.policy.NormalStudentFinePolicy {
- {static} double FINE_PER_DAY
+ double calculateFine(int)
}


class com.library.repository.BorrowTicketRepository {
- {static} String FILE_PATH
- ObjectMapper objectMapper
- List<BorrowTicket> tickets
- AtomicInteger currentMaxId
+ List<BorrowTicket> getAll()
+ BorrowTicket findById(String)
+ void add(BorrowTicket)
+ void update(BorrowTicket)
+ String generateNextId()
- void saveToFile()
- void loadFromFile()
}


class com.library.model.Book {
- String bookId
- String title
- String author
- String category
- int quantity
- double price
+ String getBookId()
+ void setBookId(String)
+ String getTitle()
+ void setTitle(String)
+ String getAuthor()
+ void setAuthor(String)
+ String getCategory()
+ void setCategory(String)
+ int getQuantity()
+ void setQuantity(int)
+ double getPrice()
+ void setPrice(double)
+ String toString()
}


class com.library.dto.BookRequestDTO {
- String bookId
- String title
- String author
- String category
- Integer quantity
- Long price
+ String getBookId()
+ void setBookId(String)
+ String getTitle()
+ void setTitle(String)
+ String getAuthor()
+ void setAuthor(String)
+ String getCategory()
+ void setCategory(String)
+ Integer getQuantity()
+ void setQuantity(Integer)
+ Long getPrice()
+ void setPrice(Long)
}


class com.library.service.BorrowReturnService {
- BorrowTicketRepository borrowTicketRepository
- BookRepository bookRepository
- ReaderRepository readerRepository
+ List<BorrowRecord> getAllRecords()
+ void borrowBook(String,String,int)
+ long returnBook(String,String)
- int countCurrentlyBorrowedBooks(String)
}


class com.library.controller.LibraryApiController {
- BookService bookService
- ReaderService readerService
- BorrowReturnService borrowReturnService
+ ResponseEntity<List<Book>> getAllBooks()
+ ResponseEntity<Book> getBookById(String)
+ ResponseEntity<Map<String,String>> addBook(BookRequestDTO)
+ ResponseEntity<Map<String,String>> deleteBook(String)
+ ResponseEntity<List<Reader>> getAllReaders()
+ ResponseEntity<Reader> getReaderById(String)
+ ResponseEntity<Map<String,String>> registerReader(ReaderRequestDTO)
+ ResponseEntity<Map<String,String>> updateReader(String,ReaderRequestDTO)
+ ResponseEntity<Map<String,String>> updateBook(String,BookRequestDTO)
+ ResponseEntity<Map<String,String>> deleteReader(String)
+ ResponseEntity<Map<String,String>> processBorrow(BorrowRequestDTO)
+ ResponseEntity<List<BorrowRecord>> getAllBorrowRecords()
+ ResponseEntity<Map<String,String>> processReturn(ReturnRequestDTO)
}


class com.library.model.StudentReader {
- {static} int MAX_BORROW_LIMIT
- {static} int FINE_PER_DAY
- {static} String READER_TYPE
+ int getMaxBorrowLimit()
+ String getReaderType()
+ int getFinePerDay()
}


class com.library.exception.LibraryException {
}
class com.library.exception.OutOfStockException {
}
class com.library.dto.ReaderRequestDTO {
- String userId
- String fullName
- String phoneNumber
- String readerType
+ String getUserId()
+ void setUserId(String)
+ String getFullName()
+ void setFullName(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ String getReaderType()
+ void setReaderType(String)
}


class com.library.model.ReturnRecord {
- String recordId
- String ticketId
- LocalDate returnDate
- long finePaid
+ String getRecordId()
+ void setRecordId(String)
+ String getTicketId()
+ void setTicketId(String)
+ LocalDate getReturnDate()
+ void setReturnDate(LocalDate)
+ long getFinePaid()
+ void setFinePaid(long)
+ String toString()
}


class com.library.repository.ReaderRepository {
- {static} String FILE_PATH
- ObjectMapper objectMapper
- List<Reader> readers
+ List<Reader> getAll()
+ Reader findById(String)
+ void add(Reader)
+ void update(Reader)
+ void delete(String)
- void saveToFile()
- void loadFromFile()
}


class com.library.model.BorrowTicket {
- String ticketId
- String readerId
- LocalDate borrowDate
- LocalDate dueDate
- LocalDate returnDate
- TicketStatus status
- long finePaid
- List<BorrowTicketDetail> details
+ String getTicketId()
+ void setTicketId(String)
+ String getReaderId()
+ void setReaderId(String)
+ LocalDate getBorrowDate()
+ void setBorrowDate(LocalDate)
+ LocalDate getDueDate()
+ void setDueDate(LocalDate)
+ LocalDate getReturnDate()
+ void setReturnDate(LocalDate)
+ TicketStatus getStatus()
+ void setStatus(TicketStatus)
+ long getFinePaid()
+ void setFinePaid(long)
+ List<BorrowTicketDetail> getDetails()
+ void setDetails(List<BorrowTicketDetail>)
+ void addDetail(BorrowTicketDetail)
+ String toString()
}


enum com.library.model.TicketStatus {
+  BORROWING
+  RETURNED
- String value
+ String getValue()
+ {static} TicketStatus fromValue(String)
}


abstract class com.library.model.User {
- String userId
- String fullName
- String phoneNumber
+ String getUserId()
+ void setUserId(String)
+ String getFullName()
+ void setFullName(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ String toString()
}


abstract class com.library.model.Reader {
- FinePolicy finePolicy
+ FinePolicy getFinePolicy()
+ {abstract}int getMaxBorrowLimit()
+ {abstract}String getReaderType()
+ {abstract}int getFinePerDay()
+ String toString()
}


class com.library.repository.BookRepository {
- {static} String FILE_PATH
- ObjectMapper objectMapper
- List<Book> books
+ List<Book> getAll()
+ Book findById(String)
+ void addBook(Book)
+ void deleteBook(String)
+ void update(Book)
- void saveToFile()
- void loadFromFile()
}


class com.library.service.policy.PriorityStudentFinePolicy {
- {static} double FINE_PER_DAY
+ double calculateFine(int)
}


class com.library.exception.GlobalExceptionHandler {
+ ResponseEntity<Map<String,Object>> handleDataNotFound(DataNotFoundException)
+ ResponseEntity<Map<String,Object>> handleOutOfStock(OutOfStockException)
+ ResponseEntity<Map<String,Object>> handleBorrowLimitExceeded(BorrowLimitExceededException)
+ ResponseEntity<Map<String,Object>> handleValidationErrors(MethodArgumentNotValidException)
+ ResponseEntity<Map<String,Object>> handleIllegalArgument(IllegalArgumentException)
+ ResponseEntity<Map<String,Object>> handleGlobalException(Exception)
- ResponseEntity<Map<String,Object>> buildErrorResponse(HttpStatus,String)
}

class com.library.model.BorrowTicketDetail {
- String bookId
- int quantity
+ String getBookId()
+ int getQuantity()
+ String toString()
+ boolean equals(Object)
+ int hashCode()
}


class com.library.model.PriorityStudentReader {
- {static} int MAX_BORROW_LIMIT
- {static} int FINE_PER_DAY
- {static} String READER_TYPE
+ int getMaxBorrowLimit()
+ String getReaderType()
+ int getFinePerDay()
}


class com.library.model.LecturerReader {
- {static} int MAX_BORROW_LIMIT
- {static} int FINE_PER_DAY
- {static} String READER_TYPE
+ int getMaxBorrowLimit()
+ String getReaderType()
+ int getFinePerDay()
}




com.library.exception.LibraryException <|-- com.library.exception.DataNotFoundException
com.library.exception.LibraryException <|-- com.library.exception.BorrowLimitExceededException
com.library.service.policy.FinePolicy <|.. com.library.service.policy.LecturerFinePolicy
com.library.service.policy.FinePolicy <|.. com.library.service.policy.NormalStudentFinePolicy
com.library.model.Reader <|-- com.library.model.StudentReader
com.library.exception.Exception <|-- com.library.exception.LibraryException
com.library.exception.LibraryException <|-- com.library.exception.OutOfStockException
com.library.model.User <|-- com.library.model.Reader
com.library.service.policy.FinePolicy <|.. com.library.service.policy.PriorityStudentFinePolicy
com.library.model.Reader <|-- com.library.model.PriorityStudentReader
com.library.model.Reader <|-- com.library.model.LecturerReader
@enduml